[[file-format-requirements]]
== File format requirements

=== General

Conformity with this document imposes requirements and restrictions beyond those
specified in ISO 32000-2 and ISO/TS 32005. <<file-format-requirements>>
specifies these additional requirements and restrictions.

Where those requirements differ with respect to the conformance level, those
differences are identified as described in <<reusable-pdf>>.

Beyond requirements for aspects of logical structure, consistent and accurate
rendering is also important to meet the objectives of this document.
Accordingly, <<file-format-fonts>> includes requirements matching those of the
corresponding clause in ISO 19005-4 (PDF/A-4) and ISO 15930-9 (PDF/X-6).

[[file-format-logical-structure]]
=== Logical structure

==== General

Conformity with this document depends on the correct use of semantically
appropriate structure elements enclosing the document's content, along with the
structure elements' properties and structure attributes (additional information
attached to the structure element).


[[file-format-logical-structure-real-content]]
==== Real content

All real content, as specified in <<ISO_32000-2,clause=14.8.2.2>>, shall be
enclosed within semantically appropriate structure elements using appropriate
attributes according to the definitions for each structure type (name objects
that identify the nature of the structure element), as defined in
<<ISO_32000-2,clause=14.8>> and <<ISO_TS_32005>>.

NOTE: The concept of real content is defined in <<ISO_32000-2,clause=14.8.2.2.1>>.

NOTE: <<ISO_TS_32005>> defines the permitted PDF 1.7 structure elements and their
inclusion rules in relation to the PDF 2.0 structure elements as defined in
<<ISO_32000-2>>.

NOTE: Some structure elements with types such as *Div* and **Span** have no
intrinsic semantics. *Div* is used to apply attributes to groups of structure
elements and their descendants (including their respective contents), while
**Span** is used to apply attributes to content.

NOTE: Whether attributes are appropriate depends on context and content
properties (see <<file-format-structure-attributes>>).

[example]
The *Placement* attribute is appropriate on a *Figure* structure element whose content is
inline in a paragraph.

[example]
The *Placement* attribute is optional when a *Figure* is placed in a block flow between two
paragraphs.

[example]
The *Placement* attribute with a value of _Block_ is appropriate for an *FENote*
structure element placed in the block flow, whereas the *Placement* attribute
with a value of _Inline_ is appropriate for an *FENote* occurring inline
contained within a *P* structure element.

[example]
The *TextDecorationType* attribute with a value of _LineThrough_ is appropriate for a
structure element enclosing struck text.

[example]
The *TextPosition* attribute with a value of _Sup_ is appropriate for
superscript characters.

Tagging shall reflect the semantics of the document's real content regardless of
how the real content was laid out, paginated, or encoded by an authoring tool.
Real content that is typically represented by a single semantic structure
element with intrinsic semantics shall not be represented by several such
structure elements of the same structure type.

[example]
A single table spanning two or more pages is correctly enclosed in a single *Table*
structure element.

NOTE: It is incorrect to have a single table spanning two or more pages enclosed
in multiple *Table* structure elements.

[example]
A single paragraph that spans two or more pages or columns is correctly enclosed
within a single *P* structure element.

NOTE: It is incorrect to have multiple lines of a single paragraph enclosed
within two or more *P* structure elements.

NOTE: How content is encoded within a content stream does not indicate the
semantically appropriate structure element(s). Unlike ISO 14289-1, this document
clearly specifies that the use of images or vector-based drawings does not
always require a *Figure* structure element.

[example]
An image solely used to represent text with no illustrative purpose can be
enclosed in a *Span* structure element with appropriate *ActualText*, as opposed
to a *Figure* structure element.

Content that is not considered real content shall be an artifact in accordance
with <<file-format-artifacts>>.


==== Logical content order

The logical content order of structure elements and their contents according to
ISO 32000-2:2020, 14.8.2.5 shall be semantically correct.

NOTE: This requirement is equivalent to WCAG 2.2, Success Criterion 1.3.2.[5]

NOTE: This document does not impose any understanding of what “semantically
correct” logical content order means to any given author. Two common example
approaches to ordering real content are to follow the order of the geographical
page layout appropriate to the language or script (e.g. top-down, left-right in
some languages), or to order the most important real content first. The author
chooses the approach and thus establishes the intended logical content order for
the document.

[example]
The correct logical content order, in a trifold brochure in English, with its
title on the right-hand panel of a landscape page, would typically locate the
title content before the rest of the brochure in the structure tree.

Artifact content intended to be consumed in a single unit shall be enclosed
within a single *Artifact* structure element or artifact marked content sequence.

NOTE: *Artifact* structure elements and artifact marked content sequences are
specified in ISO 32000-2:2020, 14.8.2.2.2.

[example]
Textual content in a page footer would usually be identified as a single artifact.

[example]
Page numbers.

If artifact content has a semantic order, the ordering of that content within
the artifact shall match the semantic order.

In some artifacts, some of the content has semantic order and some does not.
Some artifact content, particularly drawing content, does not have a semantic
order.

[example]
Paths comprising table borders have no semantic order.

[example]
Page numbers with a background have a partial semantic order in that the order
of the digits of the page number is semantic, but the relative order of the
background to the page number is not.


==== Structure types

All structure elements shall belong to, or be role mapped to, at least one of
the following namespaces specified in ISO 32000-2:2020, 14.8.6:

* the PDF 1.7 namespace;

* the PDF 2.0 namespace;

* the MathML namespace.

Other namespaces may be used by files in conformity with this document, but all
structure elements in such namespaces shall have their structure types role
mapped as described in this subclause. Such role mapping may be transitive
through other namespaces.

A structure element with no explicit namespace may be present. Such a structure
element shall have, after any role mapping, a structure type matching one of the
unique PDF 1.7 element types and as restricted by this document.

NOTE: The default standard structure namespace in ISO 32000-2 is defined as the
PDF 1.7 namespace.

NOTE: <<file-format-footnotes-endnotes>> restricts the use of the *Note*
structure type from the default standard structure namespace, and it is
therefore not permitted despite being a unique PDF 1.7 element.

Within a given explicitly provided namespace, structure types shall not be role
mapped to other structure types in the same namespace.

If custom structure types are role mapped, either directly or transitively, to
standard structure types, they shall conform to the requirements for the
standard structure types to which they are role mapped, including the
containment rules specified in ISO/TS 32005:2023, Clause 7.

[example]
A custom structure type mapped to a *Caption* standard structure type would
incur all requirements for the *Caption* structure type, including its permitted
location in the structure tree with respect to the structure element enclosing
the captioned content and the element's permitted descendants.


==== Additional requirements for specific structure types

===== General

ISO 32000-2:2020, 14.8.4 and ISO/TS 32005:2023, 5.5 describe the full list of
standard structure types for the PDF 2.0 namespace and PDF 1.7 namespace,
respectively, and provide both requirements and examples of their use.

Usage of the standard structure types shall be in accordance with the
requirements specified in both ISO 32000-2:2020, 14.7.4.2 and ISO/TS 32005 for
the PDF 2.0 namespace and PDF 1.7 namespace.

<<file-format-structure-types-document>> to <<file-format-artifact>> provide
additional requirements for specific structure types.

NOTE: <<file-format-structure-types-document>> to <<file-format-artifact>>
appear in the order in which the structure types occur in ISO 32000-2. If a
structure type does not appear in <<file-format-structure-types-document>> to
<<file-format-artifact>>, then no additional requirements apply beyond those
specified in ISO 32000-2 and ISO/TS 32005.

Requirements specific to structure attributes are addressed in <<file-format-structure-attributes>>.

[[file-format-structure-types-document]]
===== Document and DocumentFragment

The structure tree root (defined in ISO 32000-2:2020, 14.7.2) shall contain a
single *Document* structure element as its only child, as specified in ISO
32000-2:2020, Annex L and ISO/TS 32005.

The namespace for that element shall be specified as the PDF 2.0 namespace, in
accordance with ISO 32000-2:2020, 14.8.6.

NOTE: PDF/UA-2-conforming files cannot solely conform to PDF 1.7 because this
subclause requires that the *Document* structure element is in the PDF 2.0
namespace.

When a document encloses content from another document that is either a logical
document or logical document fragment as specified in ISO 32000-2:2020,
14.8.4.3, that content should be enclosed in either a *Document* structure
element or a *DocumentFragment* structure element, respectively.

The *DocumentFragment* structure type shall only be used when the author's
intent is to identify real content as originating in another document.

[example]
Excerpts from documents included inside another document.

NOTE: *DocumentFragment* is inappropriate for content (e.g. some quotations)
whose semantic intent does not rely on identification as an extract from another
document.

NOTE: Because the content is a fragment of another document, it is possible that
heading levels do not align with the overall document and would not be expected
to impact subsequent heading levels.

However, headings in that fragment would be self-consistent and not multiple
subsets of another document, as described in ISO 32000-2:2020, 14.8.4.3.


===== Part

When a grouping of content has semantic purpose unrelated to the document's
headings hierarchy, it should be enclosed within a *Part* structure element. ISO
32000-2:2020, Table 365 provides examples distinguishing the use of *Part* from
the use of the *Sect* structure type.


===== Article (Art)

Where content is semantically representative of a self-contained article in a
larger document that contains multiple such articles, that content shall be
enclosed in an *Art* structure element.

NOTE: As such, articles often include titles, their own heading levels, and
sub-structure.

Where a title applies to an entire article, the *Title* structure element shall be
included inside the *Art* structure element, either directly or indirectly.


===== Section (Sect)

When a document is divided into sections, *Sect* structure element(s) should be
used to contain the structure elements and real content that comprise such
sections. When a heading applies to an entire section, then that heading
structure element shall be contained within that *Sect* structure element.

NOTE: A section is a thematic grouping of content and structure elements,
typically with a heading structure element at its start.

NOTE: The presence of the *Sect* structure element enables efficiently skipping
sections of a document.


===== Division (Div)

Where attributes or properties are common to a set of elements, a *Div*
structure element may be used to apply those common attributes or properties to
that group of elements.

[example]
A set of paragraphs in a common language that differs from that of the
surrounding content.

NOTE: A structure element with the *Div* structure type provides no direct
semantics of its own.


[[file-format-structure-blockquote]]
===== Block quotation (BlockQuote)

*BlockQuote* shall be used to identify groups of block-level content that is
quoted from another source other than the surrounding content. For inline-level
content, refer to *Quote* (<<file-format-structures-quote>>).

NOTE: The other source can be a different author but can also be a different
article in the same document or part of a different document by the same author.

NOTE: Pull-quotes are duplicative and are therefore not considered to be block
quotes but are generally considered asides.


===== Table of Contents (TOC/TOCI)

Tables of contents shall be identified using the *TOC* and *TOCI* standard structure
types as defined in ISO/TS 32005:2023, Table 2.

NOTE: This requirement clarifies the requirement in
<<file-format-logical-structure-real-content>>, because the presence of *TOC*
and *TOCI* in the PDF 1.7 namespace, but not in the PDF 2.0 namespace, can cause
confusion regarding appropriate use of the structure types specific to tables of
contents.

Each *TOCI* in the table of contents shall identify the target of the reference
using the *Ref* entry, either directly on the *TOCI* structure element itself or
on a child structure element contained within, such as a *Reference* structure
element.

Leaders shall be identified as artifacts using one of the methods described in
<<file-format-artifacts>>.

[example]
Leaders are commonly represented by a series of dots (e.g. “…..”) separating the
item and corresponding page number.

If using an *Artifact* structure element to enclose leaders, the location of
such entries in the structure tree shall follow appropriate logical ordering and
containment.


===== Aside

The *Aside* structure type shall be used to enclose real content that occurs
outside the main flow of the content.

[example]
A sidebar containing advertising on a magazine page is typically understood as
outside the main flow of the content.

[example]
Side notes in a textbook.

If content in an *Aside* is related to the main flow of content, the parent of
the *Aside* structure element shall be the deepest structure element to which
the *Aside* structure element's content relates.

NOTE: *Aside* loosely couples its content to a single location in the structure
tree. Refer to <<file-format-printfield>> for information about the related
*FENote* structure element.


===== NonStruct

The *NonStruct* structure type may be used as the role mapping target of a
structure element with a custom structure type in a custom namespace to indicate
that the structure elements of this type and their attributes are not relevant.
Descendant structure elements and their respective content retain their
semantics.

[example]
A custom namespace can have a structure type representing pauses in spoken
language.

In such cases, *NonStruct* can be used as a role mapping target to indicate the
lack of semantic significance of that custom type in relation to the standard
structure namespaces.


===== Paragraph (P)

The *P* structure type shall be used for any content that is considered a
paragraph, regardless of the containing parent structure element and the number
of paragraphs within a parent structure element. The *P* structure type should
only be used when content is intended to be a semantic paragraph, or when there
is not a more semantically appropriate structure type. Content that is not
intended to be a semantic paragraph (e.g. a fragment of text in the *LBody* of a
list item) should not be enclosed in a *P*.

[example]
In a list item, where the content enclosed within the *LBody* is a paragraph,
then that content is tagged as a paragraph.

When more than one paragraph exists within a parent element, each paragraph
shall be tagged with a *P* structure element.

[example]
Where a footnote contains multiple paragraphs as its content, each paragraph is
enclosed within its own *P* structure element.

Where textual real content is insufficiently semantically defined by its parent
element (or enclosing ancestor elements), a *P* structure element may be used to
separate that content from surrounding content and to provide a base semantics
for the text.

NOTE: See examples in <<file-format-logical-structure-real-content>>.


===== Heading (Hn) and (H)

Conforming files shall use the explicitly numbered heading structure types
(H1-Hn) and shall not use the *H* structure type.

NOTE: The *H* structure type requires processors to track section depth, which
adds an unnecessary burden on processors and can cause ambiguity.

Where a heading's level is evident, the heading level of the structure element
enclosing it shall match that heading level.

NOTE: Standards such as ISO 14289-1 include requirements on the use of
sequential heading levels.

This document does not, in accordance with WCAG,[5] include such a requirement,
but instead focuses on ensuring that correct semantics are provided for a given
document's content.

[example]
A heading with the real content “4.5.6 Foobar” is evidently at heading level 3.


===== Title

Titles shall be identified by the *Title* standard structure type and shall not be
identified as a heading.

NOTE: This requirement is specific to real content and does not pertain to
requirements for metadata.

As titles can vary depending on exact usage, there is no intent to require a
match between real content tagged with *Title* and *dc:title* information in XMP
metadata.


[[file-format-footnotes-endnotes]]
===== Footnotes and Endnotes (FENote)

====== Structure requirements

*FENote* effectively replaces the *Note* structure type specified in ISO
32000-1:2008, 14.8.4.4.1. The *Note* standard structure type shall not be
present in conforming files.

NOTE: This does not prohibit using a *Note* structure type in any other
namespace if it is role mapped to an allowed structure type in the PDF 1.7
namespace or PDF 2.0 namespace.

Real content that refers to footnotes or endnotes (real content enclosed in
*FENote* structure elements) shall use the *Ref* entry as specified in <<file-format-intradocument>> on
the referring structure element to reference the FENote. The corresponding
*FENote* shall also use the *Ref* entry to identify all citations that reference
it. If the reference to the footnote or endnote is interactive, it shall point
to the footnote or endnote by means of a link annotation using a structure
destination, as specified in ISO 32000-2:2020, 12.3.2.3.

NOTE: *FENote* tightly couples its content to one or more locations in the
structure tree.


[[file-format-fenote-attribute-owner]]
====== *FENote* Attribute Owner

To facilitate disambiguation for the intent of specific *FENote* structure
elements, a new attribute owner should be used as defined in <<table-1>>.

[[table-1]]
.*FENote* Attribute Owner
|===
|Owner value for the attribute object's | O entry Description

|*FENote*
| Attribute governing type of footnotes, endnotes and
other types of FENote.

|===

If appropriate to the content, the attributes described in <<table-2>> should
appear on an *FENote* structure element. These attributes may be defined in
attribute objects whose *O* entry has the value _FENote_.

NOTE: It is possible that a processor does not know the type of *FENote*,
therefore an explicit *NoteType* cannot be required.

[[table-2]]
.Standard *FENote* attributes
[cols="1,1,4"]
|===
|Key |Type |Value

|*NoteType*
|name
|
_(Optional)_ The type of the *FENote* indicating a more specific semantic
definition for the *FENote*. The value of the *NoteType* shall be one of the
following and shall be applied as described here.

_Footnote_ A subtype indicating a footnote

_Endnote_ A subtype indicating an endnote

_None_ A subtype indicating that the type is not specified

Default value: None

|===


===== Subdivision (Sub)

*Sub* should be used to identify semantic subdivisions within a block-level element.


===== Label (Lbl)

Real content that labels other real content shall be enclosed within *Lbl*
structure elements.

[example]
Footnotes are often labelled by a superscript number, letter, or symbol.

NOTE: *Artifact* content can label real content. In such a case, a *Lbl*
structure element is not appropriate.

[example]
Line numbers in legal documents or source code are usually artifacts, but, when
quoted in other texts, line numbers can be real content (i.e. using *Sub* and
*Lbl* structure elements to enclose the line and its line number).

To strongly associate a label with the real content being labelled, the *Lbl*
shall be a descendant of a structure element that semantically groups both the
*Lbl* and the content being labelled. Labels and labelled content may be
enclosed within an additional substructure.

NOTE: The label is associated with the most immediate semantically significant
ancestor element that groups both the label and the content being labelled.


===== Span

The *Span* structure type shall be used inline to apply attributes and
properties to real content where all of the following are true:

* no other semantically appropriate inline structure element fully encompasses
only the relevant content;

* the properties and structure attributes do not apply to the parent structure
element;

* the semantics are not otherwise conveyed via properties on marked content
sequences.

[example]
In the middle of a paragraph, a word occurs in a different colour and the *Span*
element is used to provide the appropriate layout attribute (colour).

A *Span* structure element may be used anywhere it is permitted (see ISO/TS
32005).


[[file-format-structures-quote]]
===== Quote

The *Quote* structure type shall be used to identify inline-level content that is
quoted from another source other than the surrounding content. For block-level
quotations, see *BlockQuote* (<<file-format-structure-blockquote>>).

NOTE: Content that has quotation marks around it is not necessarily considered a
quote. For example, newspapers often use quotation marks to indicate non-factual
or interpretive statements, which are not quotes.


===== Emphasis (Em) and Strong

The *Em* and *Strong* structure types are used to indicate emphasis and should
not be used for other purposes.

NOTE: Styling is sometimes used to denote constructs in a document, for example,
keywords. The *Em* and *Strong* structure types are not intended for such
purposes.


[[file-format-annotations-link-ref]]
===== Link and Reference

A link annotation (see <<file-format-annotation-link>>) and its associated
content shall be enclosed in either a *Link* or *Reference* structure element.
The *Link* structure type should be used for external links and the *Reference*
structure type should be used for intra-document targets. *Link* annotations
that target different locations shall be in separate *Link* or *Reference*
structure elements.

NOTE: External vs intra-document linkage is a semantic concept and is not
intended to describe the syntactic mechanism used to provide such a target. For
example, a target that uses a URL to reference the file in which the link
originates can be considered an internal target and included in a *Reference*
structure element. See <<file-format-intradocument>> for additional requirements
regarding intra-document destinations.

[example]
A bibliography entry including an ISBN or URN referencing external material can
be linked using a *Link* structure element while a link to another page in the
same document can be linked using a *Reference* structure element.

Multiple link annotations shall be included in a single *Link* or *Reference*
structure element if they target the same location and are semantically
perceived to be a single link.

[example]
A URL that is split across two pages has at least two link annotations but is
semantically perceived as the same link and tagged within a single *Link*
structure element.

[example]
An authoring application can choose to produce two link annotations if content
being linked is split across multiple lines and is tagged within a single *Link*
or *Reference* structure element.

The *Reference* structure type may be used for both interactive links using link
annotations and may also be used for non-interactive content where a reference
is present.

[example]
An example of a non-interactive reference is a callout to a table in a document
from within a paragraph.

When a *Link* or *Reference* structure element encloses content that requires a
description, an *Alt* entry may be used to describe both the content and the
link.

[example]
A *Link* structure element with an *Alt* entry enclosing a link annotation and a
logo.


===== Annot

Use of the *Annot* structure type shall be in accordance with the requirements
of <<file-format-annotations>>.


[[file-format-additional-form]]
===== Form

Use of the *Form* structure type shall be in accordance with the requirements of <<file-format-forms>>.


===== Ruby (Ruby, RB, RT, RP)

Ruby is often used to provide glosses or phonetic aids adjacent to the base text
to which it applies. When ruby is used for this purpose, the *Ruby* structure
element shall be used. The *Ruby* structure element shall contain a single *RB*
structure element enclosing the annotated base text, and a single *RT* structure
element enclosing the annotating ruby text.

In cases where ruby typesetting is used for other purposes, the *Ruby* structure
element shall not be used.

NOTE: Interlinear notes typeset in a smaller ruby-like font can be tagged using
the Aside structure element.

The grouping of *Ruby* structure elements should be such that individual words
or other semantically atomic units of content are not subdivided, even when a
more granular pairing of ruby text to base text is available.

NOTE: Ensuring that the grouping of *Ruby* structure elements respects semantic
boundaries can be helpful to assistive technology.

When a portion of the ruby annotation in a ruby pair would otherwise duplicate
the base text, the overlapping characters are typically omitted from the ruby
text. When tagging such content in a single *Ruby* structure element,
*ActualText* shall be used on the RT sub-element to provide a complete textual
replacement restoring all omitted characters.

[example]
====
A document contains the Japanese word “文書”, annotated with “ぶんしょ” as a
phonetic gloss in ruby. The ruby assembly is tagged as:

[source,xml]
----
<Ruby><RB>文書</RB><RT>ぶんしょ</RT></Ruby>
----

even though the readings of the individual characters “文” and “書” are “ぶん”
and “しょ”, respectively.
====

[example]
====
A document contains the Japanese word “今日”, annotated with “きょう” as a ruby
phonetic gloss. This ruby pair cannot be subdivided any further, and as such is
tagged as:

[source,xml]
----
<Ruby><RB>今日</RB><RT>きょう</RT></Ruby>
----
====

[example]
====
When annotating the word “振り仮名” with its reading “ふりがな”, one would
ordinarily put “ふ” adjacent to “振”, and “がな” adjacent to “仮名”. The “り” is
typically not duplicated in the ruby text. When tagging this pair in a single
Ruby structure element (e.g. to meet an accessibility need), it is rendered as:

[source,xml]
----
<Ruby><RB>振り仮名</RB><RT ActualText="ふりがな">ふがな</RT></Ruby>
----
====

[example]
====
A Japanese-language document contains the English name “International
Organization for Standardization” annotated with “国際標準化 機構” as a native
ruby gloss. Since the base text forms a single semantic unit, this ruby pair is
tagged as:

[source,xml]
----
<Ruby><RB>International Organization for Standardization</RB><RT>国際標準化機構</RT></Ruby>
----
====

In some cases, phonetic glosses are rendered as parentheticals in running text,
as an alternative to ruby text, but with the same semantics. In these cases, the
*Ruby* structure element should be used. When used in this manner, the *Ruby*
structure element shall consist of a four-element subsequence: *RB*, *RP*, *RT*,
*RP*, with the content distributed as follows:

* the *RB* element shall enclose the annotated portion of the base text;

* the first *RP* element shall enclose the opening delimiter of the annotation
text;

* the *RT* element shall enclose the annotation text;

* the second *RP* element shall enclose the closing delimiter of the annotation
text.

[example]
====
Word-processing software without ruby support can annotate the word “振り仮名” as
“振り仮名(ふりがな)”. This is tagged as:

[source,xml]
----
<Ruby><RB>振り仮名</RB><RP>(</RP><RT>ふりがな</RT><RP>)</RP></Ruby>.
----
====

===== Warichu (WT, WP)

Content typeset as warichu shall be tagged in a three-element sequence
consisting of the structure elements *WP*, *WT* and *WP*, grouped inside a
*Warichu* structure element. The first *WP* structure element shall enclose the
opening delimiter separating the warichu content from the surrounding content.
The main body of the warichu content shall be enclosed in a single *WT*
structure element. The second *WP* structure element shall enclose the closing
delimiter separating the warichu content from the surrounding content.

The *Warichu* structure element shall not be used for content that is not
typeset as warichu.

NOTE: Warichu notes are semantically similar to footnotes. Some authors use
both note variants for different purposes.

[[file-format-list]]
===== List (L, LI, LBody)

If a list includes real content used as a label, such labels shall be enclosed
within *Lbl* structure elements.

If *Lbl* structure elements are present, the *ListNumbering* attribute (see
<<table-b-5>>) shall be present on the respective *L* structure element and
should have the value that most closely approximates the intended labelling
scheme; in such cases the value _None_ shall not be used.

Any real content within an *LI* structure element that is not enclosed in a *Lbl* structure element
shall be enclosed in an *LBody* structure element.

If a list continues from a previous list, the *ContinuedList* attribute shall be
present and have a value of _true_. If the previous list is present in the
document the *ContinuedFrom* attribute shall be present.

NOTE: There is value to the *ContinuedList* attribute even when the previous
list is not present, since it would help to explain the partial nature of the
content, for example, partial numbering.

If a list is continued in a subsequent list, or continues from a previous list,
a *Ref* entry should be present and, if present, it shall reference all list
segments.

[example]
====
[Conformance level for reuse] — If a list is continued in a subsequent list, or
continues from a previous list, a *Ref* entry shall be present.
====


[[file-format-table]]
===== Table (Table, TR, TH, TD, THead, TBody, TFoot)

Tables shall be regular.

NOTE: Tables are regular when the number of logical cells is equal in each row
after accounting for *RowSpan* and *ColSpan* attributes.

Row groupings formed by *THead*, *TBody* and *TFoot* structure elements shall be
regular.

NOTE: Row groups are regular when the number of logical cells is equal in each
row after accounting for *RowSpan* and *ColSpan* attributes and where cells do
not span row groups.

When a table contains header cells, that table shall provide sufficient semantic
information to accurately determine which table header cells (structure element
*TH*) pertain to other cells as specified in ISO 32000-2:2020, 14.8.5.7.

NOTE: Some tables do not have headers.

ISO 32000-2:2020, 14.8.4.8.3 describes an algorithm to determine header cells
for a cell in the table. If the algorithm results in default values for *Scope*,
as specified in ISO 32000-2:2020, 14.8.4.8.3, that are insufficient to describe
the relationship between the header cell and other cells, then the *Scope*
attribute shall be specified.

If the algorithm results in a header cell with an implicit or explicit *Scope*
that cannot describe the header/cell relationships for all the cells in the
table, then the Headers attribute shall be present for all cells to which a
header applies (see <<annex-b-table>>).

NOTE: This means that if the Headers attribute is used anywhere in the table, it
is required for all cells in the table that have headers, regardless of whether
*Scope* describes their relationships.

NOTE: The use of Headers does not negate the need for *Scope*.

As noted in ISO 32000-2:2020, Annex L, Table rows (*TR*) may include both *TH*
and *TD* cells.

NOTE: Tables can contain cells that are column headers, row headers and both
column and row headers.

Examples of table-specific attributes are provided in <<annex-b-table>>.

NOTE: End user reliance on assistive technology implies a need for as much
information as possible about the structure of tables. Table header cells and
their attributes play a key role in providing structural information.


===== Caption

All content that captions other content shall be enclosed within a *Caption*
structure element.

When present, the *Caption* element shall be a child of the structure element
enclosing the content to which the caption pertains. When the caption is
intended to be consumed before the content to which it pertains, it shall be the
first child, but when it is intended to follow the content, it shall be the last
child.


===== Figure

====== Figure semantics

As *Figure* structure elements represent fixed-layout content intended to be
consumed as a unit, a *Figure* structure element shall enclose all content used
to generate the final appearance, including background content.

A *Figure* may contain substructures to semantically describe the graphics
objects that comprise the real content's appearance.

NOTE: Graphics objects include text, vector paths, raster images and other
objects as defined in ISO 32000-2:2020, 8.2.

[example]
An organization chart enclosed by a single *Figure* structure element that
itself contains substructure to describe each subunit of the chart.

[example]
A background image intersecting an image which the author considers to be an
intrinsic part of the figure is artifact content in this case.

The presence of *Figure* structure elements implies additional requirements in
accordance with <<file-format-real-content>>.


====== Figure properties

A *Figure* structure element should have at least one of the following
properties: a. b. an alternate description (*Alt* property), as specified in ISO
32000-2:2020, 14.9.3; a replacement text (*ActualText* property) that represents
the content enclosed by the *Figure* structure element.

[example]
====
[Conformance level for accessibility] — A *Figure* structure element shall have
at least one of the above properties.
====

*Figure* elements including an *ActualText* property, irrespective of the
presence of an *Alt* property, shall be contained within the semantically
appropriate block-level element.

NOTE: Requirements for *Figure* structure elements including *ActualText* are
provided in <<file-format-real-content-actualtext>>.

NOTE: WCAG 2.2[5], also has requirements for alternative descriptions.


===== Formula

====== Mathematical expressions

Mathematical expressions shall be represented using either structure types
defined in presentation MathML, as specified in ISO 32000-2:2020, 14.8.6.3, or
as presentation MathML via the Associated Files mechanism specified in ISO
32000-2:2020, 14.13.6, or both.

NOTE: It is often easier for authors to represent mathematical expressions with
MathML via an Associated File, which is why this document supports using both
structure elements and Associated Files to represent math.

The *math* structure type, as defined in ISO 32000-2:2020, 14.8.6.3, shall occur
only as a child of a *Formula* structure element. When an associated file is
used to provide a representation of a *Formula* in presentation MathML, it shall
be associated with the respective *Formula* structure element and shall include
an *AFRelationship* entry with the value of _Supplement_.

NOTE: In general, MathML can represent the same formula in different ways.

[example]
====
Using the MathML namespace to tag the mathematics in stem:[root(3)(x)], the _3_
is tagged with MathML's *mn* element, the _x_ is tagged with *mi*, and the
entire root is tagged with *mroot*. Fully tagging every element greatly
simplifies the processor's burden to synchronize the highlighting of speech and
text.
====

[NOTE]
====
Using MathML to represent mathematical expressions allows a processor to:

* speak the expression customized to a user's needs;

* navigate the expression so that larger expressions can be more easily understood;

* convert the expression to a mathematical braille code;

* synchronize speech and highlighting of text;

* perform computations based on mathematical formulae;

* export the equation to MathML and other formats.
====


====== Non-mathematical scientific formulae

Non-mathematical scientific formulae shall be enclosed within *Formula*
structure elements and should have either an *Alt* entry or an *ActualText*
entry in its structure element dictionary.

Such formulae should be represented using either structure types defined in an
appropriate namespace or via the Associated Files (ISO 32000-2:2020, 14.13.5)
mechanism, or both.

[example]
====
[Conformance level for accessibility] — The *Formula* structure element shall
have either an *Alt* or *ActualText* entry.
====

[example]
A chemical formula, such as 2Na + 2 H20 → H2 + 2NaOH.


===== Index

The *Index* structure type shall be used to group the content, and the
sub-structure representing the full semantics for that content, which is
intended to be consumed as an index. A document may include multiple indexes
representing different types of index, in which case, each index shall be tagged
as a separate index. For each index, there should be a single *Index* structure
element enclosing all content and sub-structure comprising that content.

Within a single index item, the *Reference* structure element should enclose the
content and any interactive link that targets a location for the topic within
the document. When an index item refers to multiple different locations within
the document, each reference should be enclosed in a separate *Reference*
structure element.

[example]
If an index is an ordered list of alphabetically ordered references, then that
list is structured with an *L* structure element within an *Index* structure
element, the ordering is specified explicitly in the *ListNumbering* attribute
and in the *LBody* structure elements, *Reference* structure elements are used
to specify the internal references.

For each *Reference* structure element indicating a range of content within an
*Index* structure element, there should be a corresponding *Ref* entry within it
identifying each structure element enclosing that referenced content.


===== Bibliographic entry (BibEntry)

Content within a document that represents a bibliography entry shall be enclosed
in a *BibEntry* structure element. For such bibliography entries, there should
be a *Ref* entry in their respective structure element dictionaries that
identifies all the places (if any) within the document that refer to that
specific entry.

For a section of the document that is intended to be a bibliography, an ARIA
(Accessible Internet Rich Applications) attribute (see <<file-format-aria>>), in
accordance with WAI-ARIA Module 1.0 shall be provided for the corresponding *Sect*
structure element, indicating that the section type is _doc-bibliography_.

[example]
====
A use of ARIA roles to identify a section intended to be consumed as a
bibliography.

[source,pdf]
----
3 0 obj <<
  % Structure element for /Sect
  /Type /StructElem
  /S /Sect % Structure type
  /A <<
    /O /ARIA-1.1 % ARIA attribute owner
    /role /doc-bibliography % DPUB role "doc-bibliography"
  >>
  /NS … /P … /K … % Indirect reference to the PDF 2.0 namespace
  % Parent in structure hierarchy
  % Kids in the structure hierarchy
>>
endobj
----
====


===== Code

For content within a document that represents a fragment of computer code, that
content shall be enclosed in a *Code* structure element.

NOTE: The author determines what is considered as code.

[example]
An author can consider an ASN.1 type definition to be code.

Where the content of the *Code* structure element is intended to be consumed as
text, a textual representation of that code shall be present. A *Code* structure
element may have an *Alt* property describing the code.


[[file-format-artifact]]
===== Artifact

Use of the *Artifact* structure type shall conform with the requirements in
<<file-format-artifacts>>.


[[file-format-structure-attributes]]
==== Structure attributes

===== General

All structure attributes defined in ISO 32000-2:2020, 14.7.6, along with their
attribute owners as defined in ISO 32000-2:2020, 14.8.5.2, and in
<<file-format-fenote-attribute-owner>>, may be present in a PDF file that
conforms to this document. These attributes may be used as appropriate on all
elements, regardless of namespace. Custom attribute owners and/or namespaces may
be used.

NOTE: ISO 32000-2 adds new attributes and new attribute values.


===== Layout

Given that layout (position, colour, etc.) is not encoded into PDF content
streams in a way that strongly associates stylistic properties with content,
structure elements shall include layout attributes in accordance with ISO
32000-2:2020, 14.8.5.4 to fully convey the semantics of a given use of colour,
contrast, format or layout as necessary, to reflect all intended meaning in a
manner that addresses the broadest-possible range of consuming technologies.

NOTE: This document does not intend to require complete descriptions of page
layouts. However, layout information can help to provide assistive technology
users with information about the material they are reading.

Attributes shall be present when the relevant semantic property is present in
the content, has semantic significance and differs from any default or inherited
value. Any attribute may be present to the extent that the property exists in
the content. An attribute should not be present if the property does not exist
in the content.

NOTE: <<annex-b>> provides examples of semantic significance for the various
attribute types. Where semantic significance is marginal or unlikely, no
examples are provided.


===== Table, List, PrintField, Artifact

Standard structure types to which _Table_ (<<file-format-table>>), _List_
(<<file-format-list>>), _PrintField_ (<<file-format-printfield>>) and _Artifact_
(<<file-format-artifact>>) attributes apply shall use their respective
attributes.

NOTE: <<annex-b>> provides information on considering the semantic relevance of
attributes.

[[file-format-aria]]
===== ARIA

ARIA has utility in PDF by providing a set of roles which extend the semantic
structures defined in HTML and PDF. In PDF, ARIA roles serve at least two
purposes:

* expanding the semantics of a given structure element (e.g. identify content
enclosed in an *FENote* structure element as a footnote or endnote);

* providing semantics for non-semantic elements (e.g. identify that a Div
structure element encloses a complex infographic).

The ARIA-1.1 attribute owner, introduced in ISO 32000-2:2020, 14.8.5.2, may be
used to include ARIA (version 1.1) attributes on any structure element. ARIA
attributes shall be semantically appropriate for the use cases defined in the
WAI-ARIA Module 1.0.

ARIA (version 1.1) and DPUB-ARIA roles, if present, shall use the ARIA-1.1
attribute owner. When a role is specified, it shall not contradict the semantic
intent of the structure element to which it applies.

[example]
====
The following code represents a possible use of ARIA roles to extend the
semantics of the *Part* structure type to identify it as a glossary.

[source,pdf]
----
3 0 obj          % Structure element
<<
  /Type /StructElem
  /S /Part       % Structure type
  /A <<
    /O /ARIA-1.1 % ARIA attribute owner
    /role /doc-glossary % Digital Publishing role "doc-glossary"
  >>
  /NS 7 0 R      % Indirect reference to the PDF 2.0 namespace
  /P …           % Parent in structure hierarchy
  /K …           % Kids in the structure hierarchy
>>
endobj
7 0 obj <<       % Namespace dictionary
  /Type /Namespace
  /NS (http://iso.org/pdf2/ssn) % PDF 2.0 namespace identifier
>>
endobj
----
====

ARIA offers other attributes beyond role, including those which can define the
state and properties of a given structure element. States and properties may be
used, but do not impact rendering of the PDF, nor its interactive features.

NOTE: PDF does not have a live Document Object Model (DOM) in the way that HTML
does. There is limited interaction within PDF, and PDF processors do not expect
structure element attributes to dynamically change within the document. There is
no means by which JavaScript can directly control the attributes on a structure
element, which limits author control of these attributes to what is specified
within the file.


[[file-format-artifacts]]
=== Artifacts

==== General

Any content, except *Annotations* (see <<file-format-annotations>>), that is not
real content as specified in ISO 32000- 2:2020, 14.8.2.2 shall be explicitly
identified using one of the two methods defined in ISO 32000- 2:2020,
14.8.2.2.2.

NOTE: Rather than allow this identification to be implied by the content's
absence from the structure tree, this requirement strengthens the recommendation
to explicitly identify artifacts in ISO 32000- 2:2020, 14.8.2.2.

Where an artifact property list entry, as defined in ISO 32000-2:2020,
14.8.2.2.2, is semantically appropriate for an artifact defined solely using a
marked content sequence, they shall be present. Where artifact attributes, as
defined in ISO 32000-2:2020, 14.8.5.8, are semantically appropriate for an
*Artifact* structure element, they shall be present.

NOTE: An artifact defined without an *Artifact* structure element uses property
list entries associated with the marked content sequence. An artifact defined
with an *Artifact* structure element uses structure attributes, not property
list entries.


==== Use of the Artifact structure element

Where an artifact is only meaningful in the context of content in the structure
tree, it shall be enclosed in an *Artifact* structure element.

NOTE: The *Artifact* structure type is useful, for example, in the case of page
content that is not intended for inline reading. One such case is a legal
document in which each line is numbered for reference purposes. In this case, a
*Sub* structure element in accordance with ISO 32000-2:2020, 14.8.4.6 can enclose
each line within a *P* (paragraph) structure element. Within each Sub, the use
of an *Artifact* structure element to enclose the line-number serves to
distinguish the line-number for reading purposes while retaining the context for
reference purposes. Use of an *Lbl* structure element in this case (as implied
in ISO 32000-2:2020, 14.8.4.6) is inappropriate because the line-numbers (a
mechanical artifact, akin to pagination) would thereby be included in the
document content.


=== Text representation for content

==== General

Conformity with this document requires that text content be programmatically
determinable.


==== Unicode mapping in tagged PDF

As no pre-defined meaning is associated with Unicode Private Use Area (PUA)
values, such values in content streams shall be used only if no other valid
Unicode value is available.

NOTE: The preceding paragraph differs from ISO 32000-2:2020 only in that use of
the Unicode PUA when published meanings are available is directly contrary to
the general requirements specified in this document.


==== Replacements and alternatives for text

*ActualText* shall be used when it is necessary to convey an alternative set of
Unicode codepoints than what is generated by a processor based on ISO
32000-2:2020, 9.10.

For content mapped to a code or codes in the Unicode PUA, an *ActualText* entry
as specified in ISO 32000-2:2020, 14.9.4 should be present for this character or
for the sequence of characters of which such character is a part. In all cases,
where real content maps to Unicode PUA values, an *ActualText* or *Alt* entry
should be present.

[example]
====
[Conformance level for accessibility] — In all cases, where real content maps to
Unicode PUA values, an *ActualText* or *Alt* entry shall be present.
====

NOTE: *ActualText* and *Alt* entries cannot use the Unicode PUA (see
<<file-format-text-string>>).


==== Declaring natural language

The language of all content and text strings shall be specified.

NOTE: Where a file includes Unicode text strings with two or more languages
requiring three-letter language codes, it is possible that the language of some
text is not representable.

The default natural language for content and text strings shall be specified
using the *Lang* entry, with a non-empty value, in the document catalog
dictionary.

Changes in the natural language shall be declared using the methods described in
ISO 32000- 2:2020, 14.9.2. Changes in natural language inside text strings (e.g.
inside alternate descriptions) shall be declared using a language identifier as
described in ISO 32000-2:2020, 7.9.2.2.

When specifying language using one of the methods above, a *Lang* entry shall
resolve to a specific language.

NOTE: The declaration of natural language in the document catalog dictionary
does not imply a primary language for the document. It is the responsibility of
processors to consider how documents containing multiple languages are
represented to end users to avoid the perception that the *Lang* entry in the
document catalog dictionary represents a primary or otherwise dominant language.


[[file-format-fonts]]
==== Fonts

[[file-format-fonts-general]]
===== General

The intent of the requirements in <<file-format-fonts-general>> to
<<file-format-fonts-character-encodings>> is to ensure that the future rendering
of the textual content of a conforming file matches, on a glyph-by-glyph basis,
the static appearance of the file as originally created and, when possible, to
allow the recovery of semantic properties for each character of the textual
content. Unless a requirement specifically states that it shall only apply to
text rendered by a conforming processor, it shall apply to any font including
those used exclusively with text rendering mode 3.

NOTE: A font referenced solely in text rendering mode 3 (ISO 32000-2:2020,
9.3.6) is not rendered and is thus exempt from the requirements that impact the
visual representation of the glyphs of a font.


===== Font types

All fonts and font programs used in a conforming file, regardless of rendering
mode usage, shall conform to the requirements specified in ISO 32000-2:2020, 9.6
and 9.7, as well as to the font specifications referenced by these requirements.

NOTE: This document does not prescribe how such conformance is determined.

Multiple master fonts shall be considered a special case of Type 1 fonts. Any
requirement regarding Type 1 fonts shall also be required for multiple master
fonts.


===== Composite fonts

====== General

For any given composite (Type 0) font within a conforming file, the
*CIDSystemInfo* entry in its CIDFont dictionary and its Encoding dictionary
shall have the following relationship:

. If the *Encoding* key in the Type 0 font dictionary has a value of
_Identity-H_ or _Identity-V_, then any values *Registry*, *Ordering*, and
*Supplement* keys may be used in the *CIDSystemInfo* dictionary of the CIDFont.

. Otherwise, the corresponding values of the *Registry* and *Ordering* keys in
both *CIDSystemInfo* dictionaries shall be identical, and the value of the
*Supplement* key in the *CIDSystemInfo* dictionary of the CIDFont shall be
greater than or equal to the value of the *Supplement* key in the
*CIDSystemInfo* dictionary of the CMap.

NOTE: The requirement for the *Supplement* key ensures that the font includes
glyphs for all CIDs (Character Identifiers) which can be referenced by the CMap.


====== CIDFonts

All embedded Type 2 *CIDFonts* in the CIDFont dictionary shall contain a
*CIDToGIDMap* entry that shall be a stream mapping from CIDs to glyph indices or
the name _Identity_, as described in ISO 32000-2:2020, Table 115.


===== CMaps

All CMaps used within a file that conforms to this document, except those listed
in ISO 32000- 2:2020, Table 116, shall be embedded in that file, as described in
ISO 32000-2:2020, 9.7.5. For those CMaps that are embedded, the integer value of
the *WMode* entry in the CMap dictionary shall be identical to the *WMode* value
in the embedded CMap stream.

A *CMap* shall not reference any other *CMap* except those listed in ISO
32000-2:2020, Table 116.


===== Embedding

====== General

The font programs for all fonts used for rendering within a conforming file, as
determined by whether at least one of its glyphs is referenced from one or more
content streams, shall be embedded within that file, as defined in ISO
32000-2:2020, 9.9.

NOTE: Embedding the font programs allows any conforming processor to correctly
reproduce all glyphs in the way they were originally published without reference
to external resources.

NOTE: As discussed in ISO 32000-2:2020, 9.3.6, text rendering mode 3 specifies
that glyphs are not stroked, filled, or used as a clipping boundary. A font
referenced for use solely in this mode is therefore not rendered and is thus
exempt from the embedding requirement.

Only font programs that are legally embeddable in a file for unlimited,
universal rendering shall be used.

NOTE: This document precludes the embedding of font programs whose legality
depends upon special agreement with the copyright holder. This requirement can
create an unacceptable burden to verify the existence, validity, and longevity
of such claims.

*Embedded* fonts shall define all glyphs referenced for rendering within the
conforming file.

NOTE: As stated in <<file-format-fonts-embedding>>, subsets of a font are
acceptable if the embedded font provides glyph definitions for all characters
referenced within the file.


[[file-format-fonts-embedding]]
====== Subset embedding

Conforming files may include embedded subsets of font programs in accordance
with ISO 32000-2:2020, 9.6 and 9.7.

NOTE: The use of subsets of a font and its associated font program allows a
potentially substantial reduction in the size of conforming files.


===== Font metrics

For every font embedded in a conforming file and referenced for rendering, the
glyph width information in the font dictionary and in the embedded font program
shall be consistent for every glyph. Glyphs that are referenced only with
rendering mode 3 are exempt from this requirement.

If a composite (Type 0) font is used for rendering in vertical writing mode as
specified in ISO 32000-2:2020, 9.7.4.3 and if the associated embedded font
program contains information about vertical metrics of the glyphs, this
information shall be consistent with the values of the *DW2* and *W2* keys in
the font descriptor dictionary.

For this document, consistent is defined to be a difference of no more than
1/1000 unit in text space, consistent with ISO 32000-2:2020, 9.2.4.

NOTE: Conformance with this subclause ensures predictable font rendering,
regardless of whether a given processor uses the metrics in the font dictionary
or those in the font program.


[[file-format-fonts-character-encodings]]
===== Character encodings

For all non-symbolic TrueType fonts used for rendering, the embedded TrueType
font program shall contain at least the Microsoft Unicode (3, 1 - Platform ID =
3, Encoding ID = 1), or the Macintosh Roman (1, 0 - Platform ID = 1, Encoding ID
= 0) “cmap” subtable.

NOTE: Conformance with this requirement ensures that all necessary glyph lookups
can be carried out.

All non-symbolic TrueType fonts shall have either _MacRomanEncoding_ or
_WinAnsiEncoding_ as the value for the *Encoding* key in the Font dictionary, or
as the value for the *BaseEncoding* key in the dictionary that is the value of
the Encoding key in the Font dictionary.

In addition, all non-symbolic TrueType fonts shall not define a *Differences*
array unless all the glyph names in the *Differences* array are listed in the
Adobe Glyph List and the embedded font program contains at least the Microsoft
Unicode (3, 1 - Platform ID = 3, Encoding ID = 1) encoding in the “cmap”
subtable.

Symbolic TrueType fonts shall not contain an *Encoding* entry in the font
dictionary. The “cmap” subtable in the embedded font program shall either
contain the Microsoft Symbol (3, 0 - Platform ID = 3, Encoding ID = 0) or the
Mac Roman (1, 0 - Platform ID = 1, Encoding ID = 1) encoding.

In all cases for TrueType fonts that are to be rendered, character codes shall
be able to be mapped to glyphs in accordance with ISO 32000-2:2020, 9.6.5,
without the use of a non-standard mapping chosen by the conforming processor.


===== Unicode character maps

The font dictionary of all fonts, regardless of their rendering mode usage,
shall include a *ToUnicode* entry whose value is a CMap stream object that maps
character codes for at least all referenced glyphs to Unicode values, as
described in ISO 32000-2:2020, 9.10.3, unless the font meets at least one of the
following four conditions:

* it uses the predefined encodings _MacRomanEncoding_, _MacExpertEncoding_ or
_WinAnsiEncoding_, as defined in ISO 32000-2:2020, Annex D;

* it is a Type 1 or Type 3 font where the glyph names of the glyphs referenced
are all contained in the Adobe Glyph List, or the set of named characters in the
Symbol font, as defined in ISO 32000-2:2020, Annex D;

* it is a Type 0 font whose descendant CIDFont uses the Adobe-GB1, Adobe-CNS1,
Adobe- Japan1 or Adobe-KR-9 character collections;

* it is a non-symbolic TrueType font.

NOTE: Unicode mapping allows the retrieval of semantic properties regarding
every character referenced in the file.

If a *ToUnicode* CMap is present, the Unicode values it specifies shall all be
greater than zero (0), but not equal to either U+FEFF or U+FFFE.


===== Use of .notdef glyph

A file in conformance with this document shall not contain a reference to the
**.notdef** glyph as defined in ISO 32000-2:2020, 9.7.6.3, from any of the text
showing operators, regardless of text rendering mode, in any content stream.

NOTE: Since the **.notdef** glyph does not have any semantic value, this
requirement is present to avoid any ambiguity which can result from its use.


[[file-format-real-content]]
=== Real content without textual semantics

==== General

Real content that does not possess the semantics of text objects and does not
have an alternate textual representation shall be enclosed within *Figure*
structure elements in accordance with ISO 32000-2:2020, 14.8.4.8.5, or *Formula*
structure elements in accordance with ISO 32000-2:2020, 14.8.4.8.6, as
appropriate.

NOTE: Although encoded as text, ASCII art typically possesses semantics
appropriate to the *Figure* structure type. Likewise, although encoded (to take
one possible example) as non-textual objects, in a conforming file, a set of
paths can possess the semantics appropriate to structure elements typically used
for text, so long as they include appropriate *Alt* and/or *ActualText*
attributes.


[[file-format-real-content-actualtext]]
==== Use of ActualText

When real content is intended to be consumed as text, but is not present as text
objects, and is therefore not inherently interpretable as text by a PDF
processor, an *ActualText* property as specified in ISO 32000-2:2020, 14.9.4
shall be provided.

Structure elements that include an *ActualText* property shall be, or shall be
enclosed within, a semantically appropriate structure element.

NOTE: The definition of *ActualText* in ISO 32000-2:2020, Table 355 changed from
the definition in ISO 32000-1:2008, Table 323.

[example]
It is common for text to be represented from native PDF vector drawing
operations, i.e. without text objects.

[[file-format-text-string]]
=== Text string objects

Text strings (see ISO 32000-2:2020, 7.9.2.2) intended to be human readable shall
not use the Unicode PUA.

NOTE: Text string type is a subtype of string type and represents data encoded
using specific conventions.

It is not used for content within content streams.

[example]
Bookmarks (outlines) are an example of a user-facing text string.


=== Optional content

[example]
====
[Conformance level for accessibility] — The requirements defined in this
subclause shall only apply to the conformance level for accessibility.

All optional content configuration dictionaries in the file, including the
default optional content configuration dictionary, shall contain a *Name* entry
(see ISO 32000-2:2020, Table 96) whose value is a non-empty text string when:

. a file contains a *Configs* entry in the *OCProperties* entry of the document
catalog dictionary (see ISO 32000-2:2020, Table 29), and the *Configs* entry
contains at least one optional content configuration dictionary.

. The *AS* key shall not appear in any optional content configuration dictionary.

NOTE: This prevents the automatic adjustment of states based on usage
information (see ISO 32000-2:2020, 8.11.4.5).

NOTE: The requirements of <<file-format-fonts>> apply for all fonts used in all
optional content, even where a particular exchange does not result in some
optional content being rendered.
====


[[file-format-intradocument]]
=== Intra-document destinations

All destinations (see ISO 32000-2:2020, 12.3.2) whose target lies within the
same document shall be structure destinations (see ISO 32000-2:2020, 12.3.2.3).

NOTE: This requirement applies to link annotations providing intra-document
navigation.

Where content actionably points to other content, such as links occurring in the
context of captions, tables of contents, cross references, hyperlinks, or other
links within a document, such content shall use one or both of the following
mechanisms:

* point to the other content by means of a link annotation using a Structure
Destination (see ISO 32000-2:2020, 12.3.2.3);

* use the *Ref* entry (see ISO 32000-2:2020, Table 355) on the source structure
element to reference the target structure element.

NOTE: Consuming software can choose to provide various navigation features
leveraging the *Ref* entry to possibly provide richer navigation options than
are available with link annotations alone.

NOTE: Footnotes and endnotes have specific requirements pertaining to the *Ref*
entry (see <<file-format-footnotes-endnotes>>).


[[file-format-annotations]]
=== Annotations

[[file-format-annotations-general]]
==== General

Annotations serve multiple purposes within PDF files, including (but not limited
to):

* supporting document workflows, including review, approval and redaction;

* support for multimedia in PDF, including video, sound and 3D;

* support for interactive elements such as links and forms.

These distinct purposes mean that requirements vary for different annotation
types and even potentially depending on the specific use of a given annotation
type. This clause identifies requirements for each of these purposes except for
forms (see <<file-format-forms>>).

Annotation types deprecated in ISO 32000-2 shall not be present.

Annotations whose subtypes are not defined in ISO 32000-2 may be present and
shall be in conformity with all requirements in <<file-format-annotations>>.


==== Semantics and content

===== General

This clause describes semantic requirements for all annotation types defined in
ISO 32000-2.

Annotations (see ISO 32000-2:2020, 12.5) shall be included in the structure tree
unless explicitly excluded by the following subclauses.

When included in the structure tree, annotations shall use the most semantically
appropriate structure type in accordance with
<<file-format-logical-structure-real-content>>.

The semantics of annotation types shall be defined by the enclosing parent
structure element, or, where no semantically appropriate element exists, a
respective *Annot* structure element.

NOTE: ISO 32000-2 permits use of the *Annot* structure type for all annotation types except Widget
and *Link*, but *Annot* is not required for annotations.

The use of the *Annot* structure type does not itself imply any specific type of
annotation.

NOTE: A single *Annot* structure element can enclose multiple annotation objects
(see ISO 32000-2:2020, Table 368) when they are intended to be perceived as a
single object. See <<file-format-annotation-alt>> for requirements related to
alternate descriptions in this context.

[example]
A set of markup annotation objects, such as strikeout, caret and highlight, can
represent a single intent.

NOTE: Annotation objects cannot occur multiple times in the structure tree (see
ISO 32000-2:2020, Table 166) because only one *StructParent* is allowed.

ISO 32000-2 enables substructure within annotation appearance streams via marked
content references. Files in conformity with this document shall not use marked
content references to substructure annotation appearance streams (see ISO
32000-2:2020, Table 357).

NOTE: The effect of the above clause is to require that annotations are included
as whole objects in a single structure element.

The following subclauses specify additional requirements specific to both
classes of annotations and individual annotation types.


[[file-format-annotations-artifacts]]
===== Annotations as artifacts

Any annotation, regardless of its type, may be an artifact (see
<<file-format-artifacts>>). Annotations that are artifacts shall either not be
present in the structure tree or shall be enclosed within *Artifact* structure
elements.

In addition, annotations meeting either of the following criteria shall be
artifacts:

* The Invisible flag is set in accordance with ISO 32000-2:2020, Table 167;

* The NoView flag is set and the ToggleNoView flag is not set, in accordance
with ISO 32000- 2:2020, Table 167.

NOTE: The Hidden flag defined in ISO 32000-2, Table 167 does not imply that the
annotation is always an artifact, as that flag often changes during the user's
workflow, for example with Widget annotations.


[[file-format-annotations-markup]]
===== Markup annotations

Markup annotations defined in ISO 32000-2:2020, 12.5.6.2 and ISO 32000-2:2020,
Table 171 include the following annotation types:

* Text (also known as sticky notes) (defined in ISO 32000-2:2020, 12.5.6.4)

* Free text (defined in ISO 32000-2:2020, 12.5.6.6)

* Line (defined in ISO 32000-2:2020, 12.5.6.7)

* Square and circle (defined in ISO 32000-2:2020, 12.5.6.8)

* Polygon and polyline (defined in ISO 32000-2:2020, 12.5.6.9)

* Text markup (Highlight, Underline, Squiggly-underline, Strikeout) (defined in
ISO 32000- 2:2020, 12.5.6.10)

* Caret (defined in ISO 32000-2:2020, 12.5.6.11)

* Rubber stamp (defined in ISO 32000-2:2020, 12.5.6.12)

* Ink (defined in ISO 32000-2:2020, 12.5.6.13)

* File attachment (defined in ISO 32000-2:2020, 12.5.6.15)

* Redaction (defined in ISO 32000-2:2020, 12.5.6.23) As annotation semantics are
defined by annotation type, markup annotations shall be enclosed within *Annot*
structure elements.

NOTE: Markup annotations are only intended to annotate real content, not to
represent it.

[example]
====
[Conformance level for accessibility] — Markup annotations may omit *RC* and
*Contents* entries, but if the context of the annotation (other than a free text
annotation) is insufficient to convey its purpose, a *Contents* entry shall be
present to convey that purpose.
====

When both *RC* and *Contents* entries are present, they shall be textually
equivalent.

NOTE: Free text annotations use the *RC* and *Contents* entries to provide their
displayed text.

NOTE: Sighted users often benefit from visual clues derived from the visual
representation of annotations that other users are not able to perceive. *RC* and
*Contents* entries can provide greater context to assist with consumption.

NOTE: Content in an *RC* entry has appearance characteristics, including colour
contrast and other visual qualities, that require accessibility consideration
(for example, colour-contrast in WCAG 2.2[5]).


[[file-format-annotation-types]]
===== Annotation types

[[file-format-annotation-types-text]]
====== Text

Text annotations shall follow the requirements in
<<file-format-annotations-markup>>.

The location of text annotations in the structure tree, combined with their
respective *Contents* entries, should provide sufficient context to understand
each annotation's intent.

NOTE: <<file-format-annotations-order>> explains the rationale for this
provision.

The value of the *Name* entry should match the author's semantic intent for the
annotation.


[[file-format-annotation-link]]
====== Link

*Link* annotations should include a *Contents* entry to enrich information
available to assistive technology.

NOTE: *Link* annotations are often accessed out of context; the *Contents* entry
provides optional additional information. The *Contents* entry is also
particularly valuable in the context of link targets that are not intended to be
human-readable.

[example]
A link over the text “click here” is improved by a *Contents* entry to advise
the user regarding the link's target.

See <<file-format-annotations-link-ref>> for requirements specific to the *Link*
and *Reference* structure types.

See <<file-format-actions-uri>> for requirements specific to link annotations
that use URI actions.

The content associated with a link annotation shall be contiguous in the logical
reading order.

NOTE: This requirement implies that non-contiguous linked content always uses
multiple link annotations.


====== Free text

Free text annotations shall follow the requirements in
<<file-format-annotations-markup>>.

If the free text annotation includes an intent of _FreeTextCallout_, in
accordance with the *IT* key defined in ISO 32000-2:2020, Table 177, then the
logical reading order should align with the location of the callout's
origination.


====== Line, square, circle, polygon and polyline

Line, square, circle, polygon and polyline annotations shall follow the
requirements of <<file-format-annotations-markup>>.

[example]
For a line connecting two paragraphs, the respective *P* structure elements can
include *Ref* entries that reference the *Annot* structure element that encloses
the respective line annotation. Further, that *Annot* structure element can
include a *Ref* entry that references the related *P* structure elements.


====== Text markup

Text markup annotations shall follow the requirements of
<<file-format-annotations-markup>>.

If a text markup (highlight, underline, squiggly or strikeout) annotation is associated with
content that is non-contiguous in the logical reading order, separate text markup annotations
should be used for each contiguous unit of content.

NOTE: For a highlight spanning two pages, a single *Annot* structure element can include object
references to the two highlight annotations.


====== Caret

Caret annotations shall follow the requirements of
<<file-format-annotations-markup>>.


====== Rubber stamp

Rubber stamp annotations shall follow the requirements of
<<file-format-annotations-markup>>.

[example]
====
[Conformance level for accessibility] — If the *Name* entry, as defined in ISO
32000-2:2020, 12.5.6.12, is insufficient to describe the intent of the stamp
annotation, a *Contents* entry describing the author's intent shall be provided.
====


====== Ink

Ink annotations shall follow the requirements of
<<file-format-annotations-markup>>.

[example]
====
[Conformance level for accessibility] — A *Contents* entry describing the
author's intent shall be provided.

NOTE: As Ink annotations are freeform, descriptive information is necessary for
accessibility. For example, a handwritten signature for John Doe can be
described as “the signature of John Doe”.
====


====== Popup

Popup annotations shall not be present in the structure tree.

NOTE: Popup annotations do not define any semantics and are solely defined in
the context of their parent markup annotation.


====== File attachment

File attachment annotations shall follow the requirements of
<<file-format-annotations-markup>>.

NOTE: A sufficient description can come from the *Desc* entry of a file
specification dictionary referenced by the file attachment annotation. The
*Contents* entry of the file attachment annotation takes precedence over the
*Desc* entry if more context is required, in accordance with ISO 32000- 2:2020,
12.5.6.15.

When a file attachment annotation (as defined in ISO 32000-2:2020, 12.5.6.15)
references a file specification dictionary (as defined in ISO 32000-2:2020,
7.11.3), the file specification dictionary shall include an *AFRelationship*
entry.

NOTE: File specifications can be a string or a dictionary, as defined in ISO
32000-2:2020, 7.11.1. Using the string form is equivalent to the
*AFRelationship* entry having the value of Unspecified.


====== Sound, movie

Sound and movie annotations are deprecated in PDF 2.0 and therefore, in
accordance with <<file-format-annotations-general>>, shall not be present.

NOTE: The functions of sound and movie annotations have been replaced by
multimedia features specified in ISO 32000-2:2020, Clause 13.


====== Screen

Screen annotations shall include a *Contents* entry.

NOTE: When including video or audio using screen annotations, in support of
accessibility, third party accessibility requirements such as WCAG[5] typically
apply.


[[file-format-annotations-type-widget]]
====== Widget

Widget annotations are intended to facilitate interactive forms, see
<<file-format-forms>>.

In addition to the requirements of <<file-format-annotations-artifacts>>, a
widget annotation of zero height and width shall be an artifact in accordance
with <<file-format-artifacts>>.

NOTE: When used as part of a document workflow that makes use of signature
profiles such as PAdES-B-LTA, widget annotations associated with document
timestamp signatures are often artifacts in this sense. In such workflows, the
number of timestamps that will be added over time can typically not be predicted
in advance. Since modifying the structure tree in incremental updates after
signing complicates signature validation, it is important that invisible widgets
be exempt from any tagging requirements otherwise imposed by this document.

NOTE: Widget annotations that are artifacts, regardless of visibility, can
nevertheless have their Print flag set [e.g. in cases where compliance with ISO
19005-4 (PDF/A-4) is required].


====== Printer's mark

A printer's mark annotation shall be an artifact.


====== Trap network

Trap network annotations are deprecated in PDF 2.0 and shall not be used in
files conforming to this document, in accordance with
<<file-format-annotations-general>>.


====== Watermark

When used as real content, Watermark annotations shall follow the requirements
of <<file-format-annotations-markup>>.

NOTE: For the purposes of this document, the general requirements for markup
annotations also apply to Watermark annotations.


====== Redaction

Redaction annotations shall follow the requirements of
<<file-format-annotations-markup>>.

NOTE: The requirements of <<file-format-annotations-artifacts>> and this
subclause have no bearing on redactions themselves. They apply only to redaction
annotations. On the other hand, the redaction artifact subtype specified in ISO
32000-2:2020, Table 363 and Table 385 does not apply to redaction annotations,
but to redactions themselves (e.g. black boxes resulting from the application of
redaction annotations to the document).

Where possible (considering the use of *QuadPoints* defined in ISO 32000-2:2020,
Table 195), a single logical redaction shall be enclosed within a single
Redaction annotation.

NOTE: This requirement implies that a single redaction spanning two or more
lines on a single page would occur within a single *Redaction* annotation.


====== Projection

Projection annotations shall follow the requirements in
<<file-format-annotations-markup>>.

====== 3D and RichMedia

[example]
====
[Conformance level for accessibility] — 3D and RichMedia annotations shall
include alternate descriptions in their respective Contents entries.

NOTE: When including 3D, video or audio using 3D or RichMedia annotations, in
support of accessibility, third party requirements such as WCAG[5] typically
apply.
====


====== Other

Annotations whose subtypes are not defined in ISO 32000-2 shall meet the
requirements of this document.


[[file-format-annotations-order]]
==== Order

===== General

Many users benefit from a visual association between annotations and real
content. The placement of annotations in the structure tree, together with an
understanding of the overlap between the annotations and associated content,
ensures that annotations become part of the logical content order together with
other real content in the document.


===== Association with content

In the case of text markup, redaction and link annotations, the visual
association between content and an annotation is represented by a *QuadPoints*
entry or a *Rect* entry.

When included in the structure tree, annotations shall be placed as close to the
annotated content as possible, as either:

* a child or sibling of the applicable structure element enclosing the real
content, or

* a child of an *Annot*, *Link* or *Reference* structure element.

NOTE: The content associated with a link annotation is defined by the *Link* or
*Reference* structure element pointing to it. Any geometric association via
*QuadPoints* or *Rect* is secondary.

To more closely associate annotations to the content they annotate, *Ref*
entries may be used to associate structure elements enclosing those annotations
with one or more structure elements enclosing that real content.


===== Tab order

Every page that includes an annotation shall contain a *Tabs* entry in its page
dictionary in accordance with ISO 32000-2:2020, Table 31, and its value shall be
_A_, _W_ or _S_.

NOTE: Regardless of the value of the *Tabs* entry, each annotation's location in
the logical structure is defined by the structure tree.


[[file-format-annotation-alt]]
==== Alternative descriptions

===== Contents entries

[example]
====
[Conformance level for accessibility] — For many annotation types, the *Contents*
entry serves as one mechanism for providing alternative descriptions. If an
annotation requires an alternative description and if the *Contents* entry is
available for that purpose, the alternative description shall be included using
the *Contents* entry. However, for annotation types where the *Contents* entry is
not intended as an alternative description, and if an annotation requires an
alternative description, one of the other mechanisms defined in ISO
32000-2:2020, 14.9.3 shall be used.
====

===== Alt properties

Where an annotation has a *Contents* entry providing an alternative description
and the directly enclosing structure element has an *Alt* entry, the values of
*Alt* and *Contents* shall be identical.


[[file-format-forms]]
=== Forms

==== General

Widget annotations (see ISO 32000-2:2020, 12.5.6.19), which comprise the
interactive aspect of forms on the page, are referenced from the structure tree,
whereas fields (see ISO 32000-2:2020, 12.7.4) provide the functional
representation of forms.

Each widget annotation shall be enclosed by a *Form* structure element (see
<<file-format-additional-form>>) unless the widget annotation is an artifact.

[example]
A widget annotation used exclusively for calculations is enclosed within an
*Artifact* structure element.

A *Form* structure element shall enclose at most one widget annotation.

NOTE: *Form* structure elements include individual widgets, several of which can
together comprise a single field. As such, a *Form* structure element does not
semantically equate to a form field.

A *Form* structure element may be used to enclose the content in non-interactive
forms (forms without a widget annotation) (see <<file-format-printfield>>).

XFA forms (see ISO 32000-2:2020, Annex K) shall not be present.


[[file-format-forms-context]]
==== Context

===== General

The context for a widget annotation shall be provided through a combination of
the following:

* the real content surrounding the widget annotation;

* the position and grouping of structure elements containing the *Form*
structure element (see <<file-format-printfield>>);

* the field's label, if any (see <<file-format-forms-labels>>);

* the field's *TU* entry, if any (see <<file-format-forms-tu>>);

* the widget's label, if any (see <<file-format-forms-labels>>);

* the widget's *Contents* entry, if any (see <<file-format-forms-contents>>).

NOTE: The field's name (its *T* entry) does not contribute to conveying the
field's context.

The context provided by these means shall provide users with sufficient
information to understand an interactive form field and any associated widget
annotations.

[example]
A set of radio buttons to choose ice-cream flavours labelled “Vanilla”,
“Strawberry”, and “Chocolate” that can be fully described by their respective
labels together with the *TU* entry on the associated field, would not require a
*Contents* entry.

[example]
Each radio button in a survey form in which the column headers of a table
contain the labels “Agree” and “Disagree” for the widgets in their respective
columns, would require a *Contents* entry.

Where field types provide additional mechanisms for context, those mechanisms shall be
considered.


[[file-format-forms-labels]]
===== Labels

Where real content is used to label a widget annotation, that real content shall
be enclosed in one or several *Lbl* structure elements, which shall in turn be a
direct descendent of a *Form* structure element that also includes the object
reference to the widget annotation.

Where real content is used as the label for a group of widget annotations, that
real content shall be enclosed in one or several *Lbl* structure elements. In
turn, the *Lbl* structure element(s) shall be contained within the parent
structure element that also contains, directly or indirectly, the *Form*
structure element for each widget.

NOTE: A label for a group of *Form* structure elements is considered a form
field's label.

[example]
A form design application can allow an author to group questions comprising
arbitrary text and/or structure elements such as lists, along with form
controls, within a single semantic element.

[example]
A form design application can allow an author to group arbitrary content along
with form controls.


[[file-format-forms-contents]]
===== Contents entry

If a label for a widget annotation is not present, or if the label is
insufficient, a *Contents* entry shall be provided to supply description and
context for the widget. The *Contents* entry should not be identical to the
label because an identical entry does not add information.

NOTE: ISO 32000-2:2020, Table 166 defines the *Contents* entry as providing
alternative descriptions for some annotations, including widget annotations.

The field's *TU* entry may be used to complement or be identical to a widget's
*Contents* entry.

[example]
A cryptic label referencing information in nearby paragraphs or pages implies
the need for a *Contents* entry.

If an additional action (*AA*) entry, as defined in ISO 32000-2:2020, Table 191,
is present in a widget annotation dictionary, the respective widget's *Contents*
entry shall describe the action's intent.


[[file-format-forms-tu]]
===== TU entry

The *TU* entry in the field's dictionary is useful when there is higher-level
context that a sighted user gets from their overview of the form. A *TU* entry
may provide repetitive and useful information to facilitate easy consumption and
may also duplicate higher-level content to maximize the reader's understanding
of the field's context.

When a form field dictionary has multiple widget annotations, a *TU* entry is
often insufficient to provide full context for each annotation, thus, a label, a
*Contents* entry, or both, shall be present for each annotation to provide
additional context.

NOTE: Establishing context for AT users in complex forms presents many
challenges. The *TU* entry provides a means of conveying additional or
supplementary context.


==== Fields

===== General

Fields may be read-only.


===== Button fields

====== General

For a widget annotation that is associated with a button field, the *Contents*
entry, if present, shall reflect the intent of the *CA* entry in the widget's
appearance characteristics dictionary (see ISO 32000-2:2020, Table 192).

NOTE: The *CA* entry provides a default caption for the button which can be used
to help understand the semantic purpose of the button.


====== Push‑button

For a widget annotation that is associated with a push-button field, the
*Contents* entry, if present, shall also reflect the intent of the *RC*, *AC*,
*I*, *RI* and *IX* entries, in addition to the *CA* entry, in the widget's
appearance characteristics dictionary (see ISO 32000-2:2020, Table 192).

NOTE: These properties reflect the semantic intent of the user's interaction
with the button.

If the *TU* entry is present in the field's dictionary, it shall reflect the
intent of the *RC* entry in the widget's appearance characteristics dictionary.


====== Check boxes and radio buttons

For checkboxes and radio buttons, both the field and its associated widgets
shall conform to the requirements specified in <<file-format-forms-context>>.

[example]
A single check box button field containing multiple widget annotations
representing individual checkboxes.

[example]
A single radio button field containing multiple widget annotations representing
individual radio buttons.

NOTE: Export values are intended for processing and are not intended to be
descriptive.


===== Text fields

For text fields, when an *RV* entry (as defined in ISO 32000-2:2020, Table 228)
is present, a *V* entry (as defined in ISO 32000-2:2020, Table 226) shall also
be present, and they shall be textually equivalent.


===== Choice fields

For choice fields, the *Opt* entry specifies both the export value and the text
for each choice as displayed to the user and, in this context, the text for each
choice shall sufficiently convey its intent.

Both the field and its associated widget shall conform to
<<file-format-forms-context>>.


===== Signature fields

If the location of a signature within a document has a bearing on its legal
meaning, then the signature field's widget annotation, in accordance with
<<file-format-annotations-type-widget>>, shall be treated as real content and
shall be present in the structure tree. A signature field's widget annotation
shall be considered an artifact if it meets the criteria defined in
<<file-format-annotations-artifacts>>.

NOTE: As stated in ISO 32000-2:2020, 12.7.5.5, the location of a signature
within a document can have a bearing on its legal meaning. The exact location of
a signature relative to other content is essential to universal access.

NOTE: The Hidden flag defined in ISO 32000-2, Table 167 has no impact on whether
a given signature field's widget annotation is considered an artifact, see
<<file-format-annotations-artifacts>>.

If a portion of the appearance of a signature is represented by a graphic,
alternative text shall be provided for that graphic (see
<<file-format-annotation-alt>>).

The annotation's appearance shall not contradict the signature's metadata as
found in the signature dictionary.

NOTE: Various metadata related to the signature such as date and time of
signing, can be accessed through the signature field's signature dictionary.
Accordingly, for accessibility purposes, processing the signature's appearance
is not necessary.


[[file-format-printfield]]
==== Non-interactive forms

Non-interactive content representing a form field shall be enclosed within a
*Form* structure element. Such a *Form* element shall include appropriate
*PrintField* attributes as specified in ISO 32000-2:2020, 14.8.5.6.

NOTE: <<annex-b-3>> provides examples for *PrintField* attributes.

NOTE: There is no requirement that any specific non-interactive content (e.g.
database output formatted to look like an input form) represents a form field.

Where real content is used to label a non-interactive form field, that real
content shall be enclosed in one or several *Lbl* structure elements, which
shall in turn be a descendent of a *Form* structure element that also encloses
the real content of the form field.

Where real content is used to label a group of non-interactive form fields, that
real content shall be enclosed in one or several *Lbl* structure elements. In
turn, the *Lbl* structure element(s) shall be contained within the parent
structure element that also contains, directly or indirectly, the *Form*
structure element for each form field.


=== Metadata

==== General

The *Metadata* stream as specified in ISO 32000-2:2020, 14.3 in the document
catalog dictionary shall include a *dc:title* entry reflecting the title of the
document.

NOTE: Consistent with deployment objectives, files can include an abstract,
publisher information, publisher contact information, publication number,
author, date, and copyright information in their XMP metadata.

NOTE: Other metadata can be present in files in conformity with this document.


==== Interactive aspects

[example]
====
[Conformance level for accessibility] — The *ViewerPreferences* dictionary of
the document catalog dictionary shall be present and shall contain at least the
*DisplayDocTitle* key with a value of true, as defined in ISO 32000-2:2020,
Table 147.

NOTE: This makes the recommendation for *DisplayDocTitle* in ISO 32000-2:2020,
Table 147 into a requirement.
====


=== Navigation

==== General

Navigation features facilitate effective orientation and efficient reading,
especially on longer or highly structured documents.


==== Outlines

[example]
====
[Conformance level for accessibility] — Longer documents should include a
document outline as specified in ISO 32000-2:2020, 12.3.3.
====

Each entry in an outline dictionary should include an Action as specified in
<<file-format-actions>>.

NOTE: A document outline contains items that are often referred to as bookmarks.
Outline items can refer to destinations or invoke actions.

NOTE: This document deliberately avoids defining any specific length as
“longer”.


==== Page labels

If a page label as specified in ISO 32000-2:2020, 12.4.2 is present, it shall
represent the same number as that perceived by a user.

When a page's number is not equal to one plus the page's index, page labels
shall be present.


==== Article threads

Article threads as specified in ISO 32000-2:2020, 12.4.3, if present, should
reflect the logical content order.

NOTE: Article threads are not considered a content reuse or accessibility
technology.


[[file-format-actions]]
=== Actions

==== General

Conforming files may include actions as specified in ISO 32000-2:2020, 12.6.


==== ECMAScript actions

ECMAScript, if used, should enable processors to communicate changes to content,
visibility, focus and location in an accessible manner.


[[file-format-actions-uri]]
==== URI actions

[example]
====
[Conformance level for accessibility] — When the *IsMap* entry in a URI action
dictionary, as specified in ISO 32000-2:2020, 12.6.4.8, has a value of _true_,
equivalent functionality shall be provided elsewhere in the real content.
====


[[file-format-embedded-files]]
=== Use of embedded files

==== Descriptions for embedded files

The *Desc* entry, as specified in ISO 32000-2:2020, Table 43, shall be present
on all file specification dictionaries present in the *EmbeddedFiles* name tree
of a conforming file, and shall provide sufficient context to make clear the
intent of the embedded file.


==== Use of associated files

Files in conformity with this document may include representations that
supplement the file's real content or provide an alternate to the file's real
content.

NOTE: One use of alternative representations can be to accommodate specific
accessibility needs such as allowing derivation of Braille from MathML.

Where embedded files are intended to provide alternative or supplemental
representations of content, such files should:

* be embedded as embedded associated files as specified in ISO 32000-2:2020,
14.13.2;

* be associated with the applicable structure element as specified in ISO
32000-2:2020, 14.13.6;

* include the *AFRelationship* entry in the respective file specification
dictionaries as specified in ISO 32000-2:2020, Table 43;

* include the *Subtype* entry in the respective embedded file stream dictionary
in accordance with ISO 32000-2:2020, Table 44.
