== Introduction

This document defines a specification and best practice for a vendor- and
platform-neutral archival email format based on PDF/A known as EA-PDF for the
long-term preservation of email. This file format is compatible with either
PDF/A-3 (<<PDF_A_3>>, PDF 1.7) or PDF/A-4 (<<PDF_A_4f>> dated revision, PDF
2.0). In all cases, a valid EA-PDF file is always a valid PDF according to ISO
32000.

The primary audience of this document are preservationists with an understanding
of the needs and use-cases for preserving email, but with limited PDF technical
knowledge. This document is thus structured differently from purely technical
ISO PDF subset standards and includes best practice, background, and pragmatic
field experience information to directly support end users of EA-PDF and
developers with expertise across both email and PDF technologies. This document
records the reasoning behind design choices or limitations to ensure EA-PDF can
meet the goals of end users now (with current generation PDF software) and into
the future (with EA-PDF aware software).
